Import("dev source_path")

env, target, sources = dev.prepare_build(
    source_path, "geoip", source_glob="*.c", in_bin=False
)

env.Append(CPPDEFINES=['GEOIPDATADIR=\\"\\"', "HAVE_STDINT_H=1", "PACKAGE_VERSION=0"])

if "msvc" in env["TOOLS"]:
    env.Append(CPPDEFINES=["ssize_t=SSIZE_T"])

if "gcc" in env["TOOLS"]:
    env.Append(
        CCFLAGS=[
            "-Wno-incompatible-pointer-types",
            "-Wno-sign-compare",
            "-Wno-unused-value",
            "-Wno-unused-variable",
        ]
    )

ret = dev.build_lib(env, target, sources, dev.c_lib)
Return("ret")
