# Copyright (C) 2026 iceman50

Import("dev source_path")

env, target, sources = dev.prepare_build(
    source_path, "zstd", source_glob="*.c", in_bin=False, recursive=True
)
env.Append(CPPPATH=["#/zstd/lib", "#/zstd/lib/common"])
env.Append(CPPDEFINES=["ZSTD_DISABLE_ASM", "ZSTD_LEGACY_SUPPORT=0"])
ret = dev.build_lib(env, target, sources, dev.c_lib)
Return("ret")
